config: 'settings.yaml'
reference_path: 'Heightfields/isotropic.exr'
size: 16
crop_x: 32
crop_y: 32
texel_width: 1.0
x: 8.0
y: 8.0
sigma: 10.0
resolution: 16
iterations: 200
lr: 0.005
decay: 0.995
beta1: 0.9
beta2: 0.99
eps: 10.0E-8
