config: 'settings.yaml'
reference_path: 'Heightfields/isotropic.exr'
size: 16
crop_x: 100
crop_y: 100
texel_width: 1.0
sigma: 10.0
resolution: 32
iterations: 2000
lr: 0.0015
decay: 0.001
beta1: 0.9
beta2: 0.999
eps: 10.0E-8
